language: java
jdk:
- openjdk11
branches:
  only:
  - main
before_install:
  - echo "권한추가"
  - chmod +x gradlew
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  email:
    recipients:
    - dorothyyyj@naver.com
