language: java
jdk:
  - openjdk11
branches:
  only:
    - main
before_install:
  - chmod +x gradlew
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
script:
  - "./gradlew clean build"

before_deploy:
  - zip -r zero *
  - mkdir -p deploy
  - mv zero.zip deploy/zero.zip
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: zerogreen-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main
  - provider: codedeploy
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: zerogreen-springboot-build
    key: zero.zip
    bundle_type: zip
    application: zerogreen-springboot
    deployment_group: zerogreen-springboot-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main
notifications:
  email:
    recipients:
      - dorothyyyj@naver.com
